# File: .github/workflows/workflow.yml

<TODO Trigger Clause>

<TODO Name Clause>

jobs:

  deploy:
    <TODO VM Image Clause>
    steps:
    
    <TODO Azure Login Step>
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          <TODO Azure CLI Service Plan>
          <TODO Azure CLI WebApp>
